@DND_HP_API_HostAddress = http://localhost:5210

GET {{DND_HP_API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{DND_HP_API_HostAddress}}/HpCalculator
Accept: application/json

###

GET {{DND_HP_API_HostAddress}}/CharacterSheet
Accept: application/json

###

GET {{DND_HP_API_HostAddress}}/CharacterSheet/1
Accept: application/json

###

POST {{DND_HP_API_HostAddress}}/CharacterSheet
Content-Type: application/json

{
  "name":""
}